//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQuanCafeK19
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> TypeAccount { get; set; }
        public byte[] Avatar { get; set; }
    }
}
