//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQuanCafeK19
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.BILLINFOes = new HashSet<BILLINFO>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdCategory { get; set; }
        public int Cost { get; set; }
        public int Price { get; set; }
        public Nullable<int> Count { get; set; }
        public byte[] Avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLINFO> BILLINFOes { get; set; }
        public virtual FOODCATEGORY FOODCATEGORY { get; set; }
    }
}
